//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Albums
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int ArtistId { get; set; }
        public short LabelId { get; set; }
        public byte AlbumTypeId { get; set; }
        public int Stock { get; set; }
    
        public virtual Artists Artists { get; set; }
        public virtual Labels Labels { get; set; }
        public virtual AlbumType AlbumType { get; set; }
    }
}
