//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MusicalogEntities : DbContext
    {
    	public MusicalogEntities()
    		: base("name=MusicalogEntities")
    	{
    	base.Configuration.ProxyCreationEnabled = false;
    	}
    
    	protected override void OnModelCreating(DbModelBuilder modelBuilder)
    	{
    		throw new UnintentionalCodeFirstException();
    	}
    
    	public virtual DbSet<Albums> Albums { get; set; }
    	public virtual DbSet<Artists> Artists { get; set; }
    	public virtual DbSet<Labels> Labels { get; set; }
    	public virtual DbSet<VAlbums> VAlbums { get; set; }
    	public virtual DbSet<AlbumType> AlbumType { get; set; }
    }
}
